### ISSUE TITLE
Please create a 1.0 release

### ISSUE THREAD

**Issue by zi0r** [astroza/udptunnel#1]
Please create a 1.0 release for package maintainers

**Comment by Xcallono** [comment]
I have high doubts this is worked on anymore because of how old this issue is.

**Comment by astroza** [comment]
Hi,

  This is a toy project to me. It is not good enough to be included in a Linux distribution. 

Don't you think so?

**Comment by zi0r** [comment]
Maybe you can tag a 0.1 release instead? Any tag will do.

**Comment by astroza** [comment]
well, it's reasonable

**Comment by astroza** [comment]
v0.1 is out :P (https://github.com/astroza/udptunnel/releases)

**Comment by ROBLOXVIP735** [comment]
Yeah
