### ISSUE TITLE
Running on OSX 10.10.5 iTerm2 get "open: No such file or directory"

### ISSUE THREAD

**Issue by shoaibali** [astroza/udptunnel#2]
Compiling with just make works fine. However when I try to execute the client like so

`
./client XXX.XXX.XXX.XXX 53 <password>
`
I get ..

`
open: No such file or directory
`

I also tried running it in bash and as sudo. What other information can I provide that would help with this issue?

**Comment by astroza** [comment]
hi, you need to install tuntap module for OSX http://tuntaposx.sourceforge.net/download.xhtml
Let me know if you have more troubles.

**Comment by shoaibali** [comment]
Thanks, that sorted it.

```
 sudo !!
sudo ./client XXX.XXX.XXX.XXX 53 <password>
Password:
  + Executing scripts/osx_client.sh
add host XXX.XXX.XXX.XXX: gateway my.gateway
delete net default
add net default: gateway 10.0.0.1
+ Script execution is OK
+ Auth is OK.
+ UDP Tunnel is running.
```
