### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by birkhofflee** [astroza/udptunnel#8]
So it stops here and makes my internet inaccessible. (flushing route table solves it)

<img width="731" alt="screen shot 2017-11-21 at 10 28 55 pm" src="https://user-images.githubusercontent.com/8148095/33077975-40381634-cf0c-11e7-9074-6625846fc1f9.png">

**Comment by astroza** [comment]
send your route table before and after udptunnel client execution

**Comment by astroza** [comment]
Inactive
